# Generated by Django 5.2.8 on 2025-12-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_mensajecontacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicio',
            name='duracion_estimada',
        ),
        migrations.RemoveField(
            model_name='progresousuario',
            name='analisis_ia',
        ),
        migrations.RemoveField(
            model_name='progresousuario',
            name='foto_url',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='sexo',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], default='masculino', max_length=10),
        ),
    ]
