# Generated by Django 5.2.8 on 2025-12-14 20:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_ejercicio_duracion_estimada_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariorutina',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuariorutina',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('finalizada', 'Finalizada'), ('vencida', 'Vencida')], default='activa', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='usuariorutina',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'activa')), fields=('usuario',), name='una_sola_rutina_activa_por_usuario'),
        ),
    ]
