# Generated by Django 5.2.8 on 2025-12-15 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_usuariorutina_fecha_fin_alter_usuariorutina_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgresoSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_numero', models.IntegerField()),
                ('completado', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ejercicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progreso_series', to=settings.AUTH_USER_MODEL)),
                ('usuario_rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progreso_series', to='api.usuariorutina')),
            ],
            options={
                'unique_together': {('usuario', 'usuario_rutina', 'ejercicio', 'serie_numero')},
            },
        ),
    ]
