# Generated by Django 5.2.8 on 2025-12-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_progresoserie'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariorutina',
            name='fecha_ultima_sesion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
